### ISSUE TITLE
Cannot build OTF and TTF from Inconsolata-vf.glyphs

### ISSUE THREAD

**Issue by spwhitton** [googlefonts/Inconsolata#54]
I am attempting to follow the instructions in README.md to produce the static OTF and TTF fonts, but I run into this error:

    spwhitton@develacc:~/src/fonts-inconsolata>fontmake -g sources/Inconsolata-vf.glyphs -i -o otf
    INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
    INFO:glyphsLib.classes:Parsing "sources/Inconsolata-vf.glyphs" file into <GSFont>
    WARNING:glyphsLib.builder.components:Glyph 'Lj': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Lj': All components of the background layer of 'Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Lj': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Lj': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Eng': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Eng': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Eng': All components of the background layer of 'Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Eng': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Eng': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Eng': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Eng': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Eng': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Eng': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Oslash': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Oslash': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Oslash': All components of the background layer of 'Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Oslash': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Oslash': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Oslash': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Oslash': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Oslash': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'Oslash': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'bilabialclick': All components of the background layer of 'Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'dcroat': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'dcroat': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'dcroat': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'dcroat': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'dcroat': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'dcroat': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'dcroat': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'dcroat': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'eopenclosed': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'eopenclosed': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'eopenclosed': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'eopenclosed': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'eopenclosed': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'eopenclosed': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'eopenclosed': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'eopenclosed': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'rstroke': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'rstroke': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'rstroke': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'rstroke': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'rstroke': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'rstroke': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'rstroke': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'rstroke': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'three': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'three': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'three': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'three': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'three': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'three': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'three': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'three': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'nine': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'nine': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'nine': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'nine': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'nine': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'nine': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'nine': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'nine': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'zero.zero': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'zero.zero': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'zero.zero': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'zero.zero': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'zero.zero': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'zero.zero': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'zero.zero': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'zero.zero': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'zero.ss02': All components of the background layer of 'Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'fiveinferior': All components of the background layer of 'Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threesuperior': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threesuperior': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threesuperior': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threesuperior': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threesuperior': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threesuperior': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threesuperior': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threesuperior': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'ninesuperior': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'ninesuperior': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'ninesuperior': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'ninesuperior': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'ninesuperior': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'ninesuperior': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'ninesuperior': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'ninesuperior': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threequarters': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threequarters': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threequarters': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threequarters': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threequarters': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threequarters': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threequarters': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'threequarters': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'zerosuperior.ss02': All components of the background layer of 'Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'question': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'question': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'question': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'question': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'question': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'question': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'question': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'question': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'asterisk': All components of the background layer of 'Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'guillemetleft': All components of the background layer of 'Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'cent': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'cent': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'cent': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'cent': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'cent': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'cent': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'cent': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'cent': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'element': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'element': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'element': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'element': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'element': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'element': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'element': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'element': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'emptyset': All components of the background layer of 'Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'summation': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'summation': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'summation': All components of the background layer of 'Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'summation': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'summation': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'summation': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'summation': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'summation': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'summation': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'whiteFrowningFace': All components of the background layer of 'Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'whiteFrowningFace': All components of the background layer of 'ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'whiteFrowningFace': All components of the background layer of 'Ultra Condensed Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'whiteFrowningFace': All components of the background layer of 'Ultra Condensed ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'whiteFrowningFace': All components of the background layer of 'Ultra Expanded ExtraLight' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'whiteFrowningFace': All components of the background layer of 'Ultra Condensed Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'whiteFrowningFace': All components of the background layer of 'Ultra Expanded Regular' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'whiteFrowningFace': All components of the background layer of 'Ultra Expanded Black' will be decomposed.
    WARNING:glyphsLib.builder.components:Glyph 'numero': All components of the background layer of 'Regular' will be decomposed.
    Traceback (most recent call last):
      File "/usr/bin/fontmake", line 11, in <module>
        load_entry_point('fontmake==2.1.4', 'console_scripts', 'fontmake')()
      File "/usr/lib/python3/dist-packages/fontmake/__main__.py", line 428, in main
        project.run_from_glyphs(glyphs_path, **args)
      File "/usr/lib/python3/dist-packages/fontmake/font_project.py", line 662, in run_from_glyphs
        designspace_path = self.build_master_ufos(
      File "/usr/lib/python3/dist-packages/fontTools/misc/loggingTools.py", line 367, in wrapper
        return func(*args, **kwds)
      File "/usr/lib/python3/dist-packages/fontmake/font_project.py", line 165, in build_master_ufos
        designspace = glyphsLib.to_designspace(
      File "/usr/lib/python3/dist-packages/glyphsLib/builder/__init__.py", line 111, in to_designspace
        return builder.designspace
      File "/usr/lib/python3/dist-packages/glyphsLib/builder/builders.py", line 277, in designspace
        list(self.masters)  # Make sure that the UFOs are built
      File "/usr/lib/python3/dist-packages/glyphsLib/builder/builders.py", line 199, in masters
        self.to_ufo_glyph(ufo_glyph, layer, glyph)
      File "/usr/lib/python3/dist-packages/glyphsLib/builder/glyph.py", line 131, in to_ufo_glyph
        self.to_ufo_glyph_background(ufo_glyph, layer)
      File "/usr/lib/python3/dist-packages/glyphsLib/builder/glyph.py", line 277, in to_ufo_glyph_background
        self.to_ufo_components(new_glyph, background)
      File "/usr/lib/python3/dist-packages/glyphsLib/builder/components.py", line 44, in to_ufo_components
        to_ufo_components_background_decompose(self, ufo_glyph, layer)
      File "/usr/lib/python3/dist-packages/glyphsLib/builder/components.py", line 112, in to_ufo_components_background_decompose
        component.draw(rpen)
      File "/usr/lib/python3/dist-packages/glyphsLib/classes.py", line 2267, in draw
        pen.addComponent(self.name, self.transform)
      File "/usr/lib/python3/dist-packages/fontTools/pens/basePen.py", line 176, in addComponent
        glyph = self.glyphSet[glyphName]
    KeyError: 'Nj'
    1 spwhitton@develacc:~/src/fonts-inconsolata>

Based on README.md it is my understanding that the Glyphs.app scripts need be run only to produce the variable width font -- is that correct?  I tried checking out the v.2.000 and v2.012 tagged releases but get the same error for those.

fontmake 2.1.4 on Debian unstable.

Thank you!

**Comment by CrendKing** [comment]
The "Building the family" section says

> To build the fonts we must load sources/Inconsolata-vf.glyphs in Glyphs and do the following

Since the script is unusable without Glyphs, is Mac OS X required to build the font at all? If so, can you relax the requirement so Linux and Windows users can build too.
